services:
  neo4j:
    image: neo4j:latest
    container_name: bitcoin_graph
    # restart: always
    ports:
      - "7474:7474"  # Web UI
      - "7687:7687"  # Bolt Protocol for Django
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data
    networks:
      - bitcoin_network

  django:
    build: .
    container_name: bitcoin_django
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - bitcoin_network

networks:
  bitcoin_network:
    driver: bridge