services:
  mongodb:
    image: mongo:4.4
    container_name: darkweb_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  crawler:
    build: .
    container_name: darkweb_crawler
    depends_on:
      - mongodb
    env_file:
      - .env  # Load .env variables for the crawler
    volumes:
      - .:/app
    # restart: always

volumes:
  mongo_data: