services:
  neo4j:
    image: neo4j:latest
    container_name: bitcoin_graphs
    ports:
      - "7474:7474" # Neo4j Browser
      - "7687:7687" # Bolt Protocol for Neo4j connections
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - scraper_neo4j_data:/data
    networks:
      - bitcoin_network
  
  # backend:
  #   build: ./backend
  #   container_name: neo4j_backend
  #   volumes:
  #     - ./backend:/app 
  #     - /app/node_modules
  #   ports:
  #     - "4000:4000"  # ✅ Exposes GraphQL API
  #   networks:
  #     - bitcoin_network
  #   depends_on:
  #     - neo4j

  # frontend:
  #   build: ./frontend
  #   container_name: neo4j_react
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "5173:5173" # React app accessible at localhost:3000
  #   networks:
  #     - bitcoin_network
  #   depends_on:
  #     - neo4j

networks:
  bitcoin_network:
    driver: bridge

volumes:
  scraper_neo4j_data:
    external: true
