services:
  neo4j:
    image: neo4j:latest
    container_name: bitcoin_graph
    # restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data

  scraper:
    build: .
    container_name: bitcoin_scraper
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    volumes:
      - .:/app
    # restart: always

volumes:
  neo4j_data: